---
title: "Gesundheitsbericht Infektionsschutz"
author: "Jakob Schumacher"
date: "7 10 2019"
output:
  html_document: default
  word_document: default
---


# Hauptbotschaften
- XX % der Reinickendorfer erleiden eine Magen-Darm-Grippe 
- Reinickendorf ist Legionellenhochburg in Deutschland
- Reinickendorfer Kindern fehlen Impfungen
- In Reinickendorf gab es XXX Fälle an multiresistenten Erregern
- Es gab XXX Ausbrüche von infektiösen Ausbrüche in Reinickendorf

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)
library("here")
library("pdftools")
library("knitr")
library("ISOweek")
library("lubridate")
suppressMessages(library("tidyverse"))
suppressMessages(setwd(here::here()))
library(plotly)


readSurvstat <- function(file){
  
  # Unzipping of the given file
  unzip(file)

  # Read in the Info.pdf that goes along with every Survstat-Zip-File
  metadata <- pdf_text("Info.pdf") %>% str_replace_all("\n", "")
  Datenstand <- str_match(metadata, "Abfragezeitpunkt (.*?) Sprache")[2]
  Datenstand <- str_trim(Datenstand)
  Spalte <- str_match(metadata, "Spaltenmerkmal (.*?) Anzeigeoptionen")[2]
  Spalte <- str_replace_all(Spalte, "\\s|-", "")
  Zeile <- str_match(metadata, "Zeilenmerkmal  (.*?) Spaltenmerkmal")[2]
  Zeile <- str_replace_all(Zeile, "\\s|-", "")
  Filter <- str_match(metadata, "Filtereinstellungen  (.*?) Zeilenmerkmal")[2]
  Filter <- str_split(Filter, "\\s{5}", simplify = TRUE) 
  Filter <- str_subset(Filter, pattern = "[:alnum:]")
  Filter <- str_trim(Filter)
  Referenzdefinition <- ifelse(str_detect(paste(Filter, collapse = ""), "Referenzdefinition"), Filter[(str_which(Filter, "Referenzdefinition") + 1)], "Nein")
  Ort <- ifelse(str_detect(paste(Filter, collapse = ""), "Bundesland"), Filter[(str_which(Filter, "Bundesland") + 1)], "Deutschland")
  Anzeigeoptionen <- str_match(metadata, "Anzeigeoptionen (.*?) Datenstand zur")[2]
  Anzeigeoptionen <- str_split(Anzeigeoptionen, "\\s{5}", simplify = TRUE)
  Anzeigeoptionen <- str_subset(Anzeigeoptionen, pattern = "[:alnum:]")
  Maßzahl <- Anzeigeoptionen[str_which(Anzeigeoptionen, "Inzidenz anstatt Anzahl anzeigen")]
  Maßzahl <- ifelse(str_trim(str_split(Maßzahl, "\\:", simplify = TRUE)[[2]]) == "Nein", "Anzahl", "Inzidenz")
  Quellenangabe <- str_split(metadata, "»|«", simplify = TRUE)[[2]]
  
  # Read in the data file 
  data <- read.delim("Data.csv", sep = "\t", skip = 1, fileEncoding = "UTF-16LE", blank.lines.skip = TRUE, stringsAsFactors = FALSE)
  
  # Remove empty line which gets introduced by reading the survstat format file
  data <- data[-c(1),] 
  
  # Tidy up
  data <- data %>% 
    gather(key = "column", value = "n", -X) %>% 
    mutate(n = ifelse(n == "", 0, n)) %>% 
    mutate(n = ifelse(is.na(n), 0, n)) %>% 
    mutate(n = str_replace(n, ",", ".")) %>%  
    mutate(n = as.numeric(n)) %>% 
    mutate(X = as.factor(X)) %>% 
    rename(!!Spalte := column) %>% 
    rename(!!Maßzahl := n) %>% 
    rename(!!Zeile := "X") %>% 
    mutate(Quellenangabe = Quellenangabe)
  
  
  # Change Meldejahr mit Woche to date
  if (str_detect(paste(names(data), collapse = ""), "Meldejahrmitwoche")) {
    data <- data %>% 
      mutate(Meldejahrmitwoche = str_replace(Meldejahrmitwoche, ".K", "-")) %>% 
      mutate(Meldejahrmitwoche = str_replace(Meldejahrmitwoche, "X", "")) %>% 
      mutate(Meldejahrmitwoche = paste0(Meldejahrmitwoche, "-", 3)) %>% 
      mutate(Meldejahrmitwoche = ISOweek::ISOweek2date(Meldejahrmitwoche)) 
  }
  
  # Attach the information from the metadata on filter
  data <- data %>% 
    mutate(Referenzdefinition =  Referenzdefinition) %>% 
    mutate(Ort =  Ort) 
  
  # Hand over the data object
  data
}

```


```{r}

# Read in the data
data <- bind_rows(
  readSurvstat("data/FallzahlKrankheit_Jahrwoche_NurReinickendorf.zip")  %>% 
    left_join(readSurvstat("data/InzidenzKrankheit_Jahrwoche_NurReinickendorf.zip")),
  readSurvstat("data/FallzahlKrankheit_Jahrwoche_Deutschland.zip") %>% 
    left_join(readSurvstat("data/InzidenzKrankheit_Jahrwoche_Deutschland.zip"))
  )
 
```



# Grafiken von Infektionskrankheiten
```{r, results='asis'}
# Set the variables 

cuttingepoint1 = 10
cuttingepoint2 = 100


krankheitsliste <- data %>%
  mutate(Krankheit = as.character(Krankheit)) %>%
  pull(Krankheit) %>%
  unique()


 # i = krankheitsliste[6]
# data <- head(data, 2000)

for (i in krankheitsliste) {
  
    cat("#", i, "\n")
    cat("\n")
  
  # Autodecision which plot to take
  totalnumber <- data %>% filter(Krankheit == i) %>% summarise(sum(Anzahl)) %>% pull()
  autodecision <- "1 year"
  if (totalnumber > cuttingepoint1) autodecision <- "1 year"
  if (totalnumber > cuttingepoint2) autodecision <- "3 months"
  
  # Make the graphs description
  Quellenangabe <- data$Quellenangabe[1]
  title <- paste("Fälle von", i)
  subtitle <- paste(data$Ort[1], 
                    "\n vom", 
                    strftime(min(data$Meldejahrmitwoche), format = "%d.%m.%Y"),
                    "bis zum",
                    strftime(max(data$Meldejahrmitwoche), format = "%d.%m.%Y"))
  
  
  
  # Filter the data and floor to the autodecision
  df <- data %>% filter(Krankheit == i) %>%
    mutate(Meldejahrmitwoche = floor_date(Meldejahrmitwoche, autodecision)) %>%
    group_by(Meldejahrmitwoche, Ort) %>% 
    summarize(Anzahl = sum(Anzahl))
  
  if (totalnumber > cuttingepoint1) {
    # Plot the graph
  print(
    ggplot(data = df, aes(y = Anzahl, x = Meldejahrmitwoche)) +
    geom_bar(stat = "identity", fill = "steelblue") +
      facet_grid(Ort~., scales = "free") +
    labs(title = title,
              subtitle = subtitle,
              caption = paste("Datenquelle:", Quellenangabe)) +
    theme_classic() 
  )
  
  # Inzidenz
    df <- data %>% filter(Krankheit == i) %>%
      mutate(Meldejahrmitwoche = floor_date(Meldejahrmitwoche, "1 year")) %>%
      group_by(Meldejahrmitwoche, Ort) %>% 
      summarize(Inzidenz = mean(Inzidenz)) %>% 
      filter(Meldejahrmitwoche < as.Date("2020-01-01", origin = "1970-01-01"))  
  
  print(
    ggplot(data = df, aes(y = Inzidenz, x = Meldejahrmitwoche, color = Ort)) +
      geom_line(stat = "identity") +
      geom_point() +
      labs(title = title,
           subtitle = subtitle,
           caption = paste("Datenquelle:", Quellenangabe)) +
      theme_classic() +
      expand_limits(y = 0)
  )
  
  
  
  }
  
  else {
    cat("\n")
    cat("\n")
    cat("\n")
    cat(paste("In",data$Ort[1],"sind zwischen dem", strftime(min(data$Meldejahrmitwoche), format = "%d.%m.%Y"), "und dem", strftime(max(data$Meldejahrmitwoche), format = "%d.%m.%Y"), totalnumber, " Fälle an", i, "aufgetreten"))
  }
    cat("\n")
    cat("\n")
    cat("\n")
    cat("\n")
}

```





```{r}
# 

# 
# data <- data %>% 
#   group_by(Krankheit) %>% 
#   summarise(Gesamtanzahl = sum(Anzahl)) %>% 
#   mutate(autodecision = ifelse(Gesamtanzahl > 50, "Inzidenz", "Unentschieden")) %>% 
#   mutate(autodecision = ifelse(Gesamtanzahl < 10, "Textdarstellung", "Anzahl")) 

```